/**
 * Line-item presets by division — one-tap rows for invoices and estimates.
 * Prices are Southeast-US 2025–26 midpoints (install-inclusive). JR edits
 * quantity and price per job. Used by the invoice editor, the estimate wizard
 * and the AI's list_line_presets tool.
 */

import type { PresetDivision } from '@/lib/option-presets';

export interface LinePreset {
  description: string;
  unit: string;          // LS, LF, SF, SQ, EA, CY, TON, HR, DAY, AC, VF, SHEET, SPACE, PR, %
  unit_price: number;
  qty?: number;          // default quantity (1 if omitted)
}

const L = (description: string, unit: string, unit_price: number, qty?: number): LinePreset =>
  ({ description, unit, unit_price, ...(qty ? { qty } : {}) });

export const GENERAL_LINE_PRESETS: LinePreset[] = [
  L('Mobilization / demobilization', 'LS', 2500),
  L('Permit & inspection fees', 'LS', 350),
  L('Labor', 'HR', 85),
  L('Equipment (operator + machine)', 'HR', 165),
  L('Materials allowance', 'LS', 1000),
  L('Dumpster & haul-off (20 yd)', 'EA', 550),
  L('Deposit — 50% to schedule', 'LS', 0),
  L('Progress payment', 'LS', 0),
  L('Final payment on completion', 'LS', 0),
  L('Change order', 'LS', 0),
  L('Service call / diagnostic (first hour)', 'HR', 175),
  L('Emergency / after-hours premium', 'LS', 250),
  L('Travel / trip charge', 'EA', 75),
];

export const LINE_PRESETS_BY_DIVISION: Record<PresetDivision, LinePreset[]> = {
  utilities: [
    L('Mobilization / demobilization (utility crew)', 'LS', 3000),
    L('6" C900 DR18 water main, open cut, incl. bedding', 'LF', 58),
    L('8" C900 DR18 water main, open cut', 'LF', 70),
    L('8" ductile iron Class 350 water main, poly-wrapped', 'LF', 92),
    L('8"×6" wet tap w/ tapping sleeve & valve, complete', 'EA', 6750),
    L('3/4"–1" domestic water service (corp, tubing, setter, box)', 'EA', 1850),
    L('Fire hydrant assembly, complete', 'EA', 8000),
    L('6" gate valve & box', 'EA', 2600),
    L('8" gate valve & box', 'EA', 3600),
    L('8" PVC SDR-35 sanitary sewer, 6–10\' depth', 'LF', 62),
    L('4" PVC SDR-35 sewer lateral, incl. cleanout', 'LF', 35),
    L('4\' dia. precast sanitary manhole, 0–6\'', 'EA', 6500),
    L('Sanitary manhole extra depth', 'VF', 300),
    L('Sewer service connection / tap to main (core & boot)', 'EA', 1850),
    L('15" HDPE storm pipe', 'LF', 58),
    L('18" HDPE storm pipe', 'LF', 70),
    L('24" HDPE storm pipe', 'LF', 85),
    L('18" RCP Class III storm pipe', 'LF', 82),
    L('2\'×2\' precast catch basin w/ frame & grate', 'EA', 3450),
    L('Precast flared end section / headwall', 'EA', 1700),
    L('Grinder pump station (simplex, residential)', 'EA', 6750),
    L('Trench rock excavation', 'CY', 145),
    L('Saw-cut & asphalt trench patch', 'SF', 11),
    L('Flowable fill backfill', 'CY', 190),
    L('Hydrostatic test, chlorination & bac-T sampling', 'LS', 2500),
    L('CCTV / mandrel test (sewer)', 'LF', 3),
    L('Directional bore crossing', 'LF', 90),
    L('Tracer wire & warning tape', 'LF', 1.25),
    L('Dewatering / well-pointing', 'DAY', 3000),
    L('Traffic control / lane closure', 'DAY', 1500),
    L('SC811 + private utility locate (GPR)', 'LS', 650),
    L('As-built survey / GPS locate', 'LS', 1500),
    L('Utility tap / capacity fee (pass-through)', 'LS', 0),
  ],
  septic: [
    L('SCDES onsite wastewater permit & site evaluation coordination', 'LS', 525),
    L('1,000 gal precast 2-compartment septic tank, set', 'EA', 1800),
    L('1,250 gal precast septic tank, set', 'EA', 2200),
    L('1,500 gal precast septic tank, set', 'EA', 2700),
    L('Excavate, bed & backfill tank', 'EA', 900),
    L('4" Sch-40 building sewer, house to tank', 'LF', 24),
    L('Distribution box, precast, w/ levelers', 'EA', 350),
    L('Conventional gravel trench 36" w/ 4" perf pipe', 'LF', 35),
    L('Infiltrator Quick4 Plus chamber trench', 'LF', 38),
    L('Low-pressure pipe (LPP) field w/ laterals & turn-ups', 'LF', 48),
    L('Pump tank 500 gal w/ effluent pump, floats, simplex panel', 'EA', 4750),
    L('Risers & lids to grade, 24"', 'EA', 300),
    L('Effluent filter', 'EA', 175),
    L('Mound fill sand, imported & placed', 'CY', 60),
    L('Aerobic treatment unit (ATU) installed w/ aerator & panel', 'EA', 12500),
    L('Drip dispersal zone w/ headworks, filter, flush valves', 'LS', 14000),
    L('Electrical for pump / ATU (dedicated circuit, disconnect)', 'LS', 1050),
    L('Engineered / soil-scientist design', 'LS', 2750),
    L('Final grade, straw & seed over disturbed area', 'SF', 0.25),
    L('Septic tank abandonment (pump, crush, fill)', 'EA', 1300),
    L('Septic pump-out & inspection', 'EA', 500),
    L('Drain field repair (partial trench replacement)', 'LS', 5500),
    L('Full drain field replacement', 'LS', 11500),
  ],
  grease_traps: [
    L('1,000 gal precast concrete grease interceptor, set & plumbed', 'EA', 8750),
    L('1,500 gal precast grease interceptor', 'EA', 12000),
    L('2,000 gal precast grease interceptor', 'EA', 15000),
    L('Excavation, bedding, backfill for interceptor', 'EA', 2500),
    L('Schier GB-250 high-capacity interceptor, installed', 'EA', 8250),
    L('Schier GB-50 / Zurn 50 GPM indoor hydromechanical, installed', 'EA', 4000),
    L('4" PVC kitchen waste line, trenched', 'LF', 42),
    L('Sampling port / inspection manhole', 'EA', 1700),
    L('H-20 risers & cast-iron lids', 'EA', 650),
    L('Core drill & connect to sanitary sewer', 'EA', 1300),
    L('Interior slab saw-cut, remove & repour', 'SF', 22),
    L('Vented flow-control fitting', 'EA', 425),
    L('Solids interceptor / strainer', 'EA', 650),
    L('Plumbing permit & FOG program coordination', 'LS', 700),
    L('Grease trap pump-out (1,000 gal)', 'EA', 425),
    L('Grease trap inspection & report', 'EA', 300),
  ],
  grading: [
    L('Mobilization (dozer / excavator / haul)', 'LS', 2750),
    L('Clear & grub, light', 'AC', 2500),
    L('Clear & grub, heavy wooded', 'AC', 7500),
    L('Forestry mulching', 'AC', 3750),
    L('Stump removal', 'EA', 325),
    L('Topsoil strip & stockpile', 'CY', 4.5),
    L('Mass excavation / cut-fill', 'CY', 6),
    L('Import structural fill, placed & compacted', 'CY', 26),
    L('Haul off excess spoil', 'CY', 18),
    L('Building pad prep & compaction', 'SF', 3.75),
    L('Finish grade', 'SF', 0.35),
    L('Gravel driveway, 12\' wide, 4" ABC', 'LF', 9),
    L('Crusher run / ABC stone, delivered & spread', 'TON', 38),
    L('#57 stone, delivered & spread', 'TON', 42),
    L('15" HDPE driveway culvert, installed', 'LF', 62),
    L('Rip-rap, placed', 'TON', 95),
    L('Silt fence', 'LF', 3.75),
    L('Construction entrance (stone, 50\'×20\')', 'EA', 1850),
    L('Inlet protection', 'EA', 150),
    L('Rock check dam', 'EA', 450),
    L('Temporary seeding / mulch', 'AC', 2250),
    L('Hydroseed', 'SF', 0.15),
    L('Sod, installed', 'SF', 1.1),
    L('Segmental block retaining wall', 'SF', 42),
    L('Geogrid reinforcement', 'SY', 4.5),
    L('Wall drainage stone & perforated pipe', 'LF', 12),
    L('Rock excavation', 'CY', 175),
    L('French drain / yard drain', 'LF', 38),
    L('Demolition of existing structure', 'LS', 9000),
    L('Survey stakeout / GPS model', 'LS', 1800),
    L('SWPPP / NPDES plan & inspections', 'LS', 5000),
  ],
  concrete: [
    L('Concrete driveway 4", fiber, broom, on stone base', 'SF', 9),
    L('Concrete driveway 5" w/ rebar (truck-rated)', 'SF', 11),
    L('Garage / shop slab 4" w/ vapor barrier, trowel finish', 'SF', 7.5),
    L('Commercial slab 6" 4,000 psi w/ #4 rebar', 'SF', 12.5),
    L('Sidewalk 4" broom finish, 4\' wide', 'LF', 38),
    L('Patio 4" broom finish', 'SF', 10),
    L('Stamped concrete', 'SF', 21),
    L('Exposed aggregate', 'SF', 14.5),
    L('Poured steps, per riser, 4\' wide', 'EA', 375),
    L('Continuous footing 16"×8"', 'LF', 28),
    L('Monolithic slab turn-down edge', 'LF', 32),
    L('Pier footing 24"×24"×12"', 'EA', 225),
    L('8" CMU foundation / stem wall, grouted', 'SF', 22),
    L('Brick veneer, installed', 'SF', 21),
    L('Manufactured stone veneer, installed', 'SF', 24),
    L('Natural thin-stone veneer, installed', 'SF', 40),
    L('Concrete retaining wall, poured 8"', 'SF', 58),
    L('Demo & haul existing concrete', 'SF', 3.75),
    L('Concrete pump (boom truck)', 'DAY', 1600),
    L('Curb & gutter 24"', 'LF', 28),
    L('Concrete dumpster pad 6" 12×12 w/ approach', 'EA', 5000),
    L('Bollard, 6" steel, concrete-filled', 'EA', 1100),
    L('Cure & seal', 'SF', 0.75),
    L('Integral color', 'SF', 2.25),
    L('Saw-cut control joints', 'LF', 2.5),
    L('Rebar #4 @ 12" grid', 'SF', 2),
    L('4" stone base', 'SF', 1.4),
  ],
  roofing: [
    L('Tear-off & dispose, 1 layer asphalt', 'SQ', 140),
    L('Architectural shingle, installed', 'SQ', 390),
    L('3-tab shingle, installed', 'SQ', 325),
    L('Designer shingle, installed', 'SQ', 800),
    L('Impact-resistant Class 4 shingle, installed', 'SQ', 480),
    L('Synthetic underlayment', 'SQ', 35),
    L('Ice & water shield', 'LF', 4),
    L('Drip edge, aluminum', 'LF', 2.25),
    L('Ridge vent, shingle-over', 'LF', 11.5),
    L('Hip & ridge cap shingles', 'LF', 6),
    L('Starter strip', 'LF', 2),
    L('Pipe boot flashing', 'EA', 65),
    L('Step & counter flashing at wall / chimney', 'LF', 28),
    L('Chimney cricket', 'EA', 575),
    L('Replace roof decking, 7/16" OSB', 'SHEET', 92),
    L('Standing seam 24ga Kynar panel, installed', 'SQ', 1650),
    L('Standing seam 26ga SMP panel, installed', 'SQ', 1300),
    L('Exposed-fastener 26ga metal, installed', 'SQ', 825),
    L('Metal ridge cap, closures & trim', 'LF', 11),
    L('Metal eave / rake trim', 'LF', 7),
    L('Snow guards (metal roof)', 'EA', 22),
    L('Seamless 5" aluminum gutter w/ downspouts', 'LF', 10),
    L('Seamless 6" aluminum gutter w/ downspouts', 'LF', 12.5),
    L('Gutter guards, micro-mesh', 'LF', 22),
    L('Fascia wrap, aluminum', 'LF', 8),
    L('Skylight replacement (Velux)', 'EA', 2000),
    L('Solar attic fan', 'EA', 900),
    L('Dumpster & haul-off (roofing)', 'EA', 575),
    L('Roofing permit', 'LS', 275),
    L('Roof repair service call (minimum)', 'LS', 500),
    L('Roof inspection & report', 'EA', 250),
  ],
  electrical: [
    L('200A panel upgrade, incl. permit & inspection', 'EA', 3000),
    L('Meter base & mast replacement', 'EA', 1300),
    L('100A subpanel w/ feeder ≤50 ft', 'EA', 1450),
    L('Whole-house surge protector', 'EA', 450),
    L('50A NEMA 14-50 EV / RV outlet', 'EA', 900),
    L('Hardwired 48A Level 2 EV charger, installed', 'EA', 1700),
    L('22 kW standby generator w/ 200A ATS, installed', 'EA', 12000),
    L('Gas line for generator (NG or LP)', 'LF', 35),
    L('Generator interlock kit + inlet box', 'EA', 1050),
    L('Manual transfer switch (10-circuit)', 'EA', 1400),
    L('6" LED recessed light, retrofit', 'EA', 200),
    L('Dimmer switch (Lutron)', 'EA', 170),
    L('Smart switch / dimmer (Lutron Caseta)', 'EA', 170),
    L('Ceiling fan install (existing box)', 'EA', 250),
    L('Ceiling fan w/ new wiring & fan-rated box', 'EA', 550),
    L('Dedicated 20A circuit', 'EA', 375),
    L('30A dryer / 50A range circuit', 'EA', 600),
    L('Outlet / switch add (existing circuit)', 'EA', 225),
    L('Exterior GFCI receptacle', 'EA', 275),
    L('Exterior flood / security light', 'EA', 325),
    L('Low-voltage landscape lighting, per fixture', 'EA', 225),
    L('Under-cabinet LED strip', 'LF', 35),
    L('Cat6 data drop', 'EA', 225),
    L('Smoke / CO detector, interconnected', 'EA', 135),
    L('Hot tub 50A GFCI disconnect & feed', 'EA', 1350),
    L('Mini-split 240V disconnect & circuit', 'EA', 700),
    L('Troubleshooting / service call (first hour)', 'HR', 175),
    L('Electrical permit', 'LS', 200),
  ],
  plumbing: [
    L('50 gal gas tank water heater, replace, incl. haul-away & permit', 'EA', 2000),
    L('50 gal electric tank water heater, replace', 'EA', 1600),
    L('Heat pump water heater 50 gal, installed', 'EA', 4000),
    L('Gas tankless condensing 199k BTU, incl. venting', 'EA', 5250),
    L('Expansion tank', 'EA', 250),
    L('Whole-house PEX repipe (2.5 bath)', 'LS', 7500),
    L('Copper repipe (2.5 bath)', 'LS', 13000),
    L('Toilet, supply & install (mid-grade)', 'EA', 625),
    L('Kitchen faucet, supply & install', 'EA', 525),
    L('Bathroom faucet, supply & install', 'EA', 450),
    L('Shower / tub valve replace w/ trim', 'EA', 925),
    L('Garbage disposal 3/4 HP', 'EA', 500),
    L('Water softener 48k metered, installed', 'EA', 2500),
    L('Whole-house carbon filter', 'EA', 1850),
    L('Iron / sulfur air-injection filter', 'EA', 2150),
    L('UV disinfection system', 'EA', 1050),
    L('Reverse-osmosis under-sink', 'EA', 675),
    L('Pressure reducing valve replacement', 'EA', 525),
    L('Main shutoff ball valve', 'EA', 375),
    L('Main water line 1" PEX / poly, trenched', 'LF', 35),
    L('Hose bib, frost-free', 'EA', 325),
    L('Sump pump system', 'EA', 1300),
    L('Two-way sewer cleanout', 'EA', 1400),
    L('Gas line drop (CSST / black iron)', 'EA', 850),
    L('Well pressure tank replacement', 'EA', 1250),
    L('Submersible well pump replacement', 'EA', 3500),
    L('Drain cleaning (main line)', 'EA', 375),
    L('Hydro-jetting', 'EA', 650),
    L('Drain camera inspection', 'EA', 350),
    L('Service call / diagnostic (first hour)', 'HR', 175),
    L('Plumbing permit', 'LS', 225),
  ],
  repairs: [
    L('Treated deck, 5/4 decking, 2×8 frame, footings, wood rail', 'SF', 38),
    L('Composite deck (Trex Enhance / Select), composite rail', 'SF', 68),
    L('Composite deck premium (Transcend / Azek), aluminum rail', 'SF', 92),
    L('Deck stairs, treated, per riser (4\' wide)', 'EA', 225),
    L('Aluminum railing', 'LF', 85),
    L('Composite railing', 'LF', 60),
    L('Cable railing', 'LF', 115),
    L('Concrete deck footing, dug & poured', 'EA', 300),
    L('Deck demo & haul', 'SF', 8),
    L('Deck stain & seal', 'SF', 3),
    L('Pergola, treated / cedar', 'SF', 52),
    L('Screened enclosure on existing porch', 'SF', 22),
    L('6\' treated privacy fence, dog-ear', 'LF', 35),
    L('6\' cedar privacy fence', 'LF', 49),
    L('6\' vinyl privacy fence', 'LF', 52),
    L('4\' vinyl picket fence', 'LF', 38),
    L('4\' chain link galvanized', 'LF', 20),
    L('6\' chain link galvanized', 'LF', 25),
    L('4\' aluminum ornamental fence', 'LF', 45),
    L('3-rail farm / ranch wood fence', 'LF', 24),
    L('Walk gate 4\'', 'EA', 450),
    L('Double drive gate 10–12\'', 'EA', 1400),
    L('Automatic gate operator', 'EA', 4250),
    L('Fence removal & haul', 'LF', 7),
    L('Drywall patch, small (≤1 SF)', 'EA', 225),
    L('Drywall water-damage repair (1–10 SF)', 'EA', 450),
    L('Drywall hang / tape / finish, new', 'SF', 2.85),
    L('Popcorn ceiling removal & refinish', 'SF', 4.5),
    L('Interior paint, walls, 2 coats', 'SF', 2.5),
    L('Interior paint, walls + ceilings + trim', 'SF', 4.25),
    L('Exterior paint, siding & trim', 'SF', 2.75),
    L('Cabinet painting (kitchen, spray)', 'LS', 5000),
    L('Interior prehung door, installed', 'EA', 475),
    L('Exterior steel entry door, installed', 'EA', 1250),
    L('Fiberglass entry door w/ glass, installed', 'EA', 2350),
    L('Sliding patio door 6\', installed', 'EA', 2650),
    L('Storm door, installed', 'EA', 675),
    L('Vinyl replacement window (insert)', 'EA', 725),
    L('Fiberglass replacement window', 'EA', 1425),
    L('Crown / baseboard trim', 'LF', 10),
    L('Soffit / fascia repair', 'LF', 13),
    L('Siding repair (vinyl / Hardie patch)', 'EA', 600),
    L('Rotten wood replacement (jamb / sill / trim)', 'EA', 525),
    L('Caulk & seal exterior', 'LS', 500),
    L('Pressure washing (house)', 'EA', 425),
    L('Gutter cleaning', 'EA', 250),
    L('Attic ladder, installed', 'EA', 675),
    L('TV wall mount', 'EA', 250),
    L('Handyman labor', 'HR', 100),
    L('Dumpster (10–20 yd)', 'EA', 475),
  ],
  residential: [
    L('Plans, engineering & permits (custom home)', 'LS', 15000),
    L('Site work / grading / driveway', 'LS', 30000),
    L('Footings & crawlspace foundation (CMU)', 'SF', 17),
    L('Monolithic slab foundation', 'SF', 11),
    L('Framing, labor & lumber package', 'SF', 36),
    L('Roof trusses', 'SF', 5.5),
    L('Windows & exterior doors (allowance)', 'EA', 675),
    L('Vinyl siding, installed', 'SF', 6.5),
    L('Hardie lap siding ColorPlus, installed', 'SF', 12),
    L('Board & batten siding, installed', 'SF', 13),
    L('Brick veneer, installed', 'SF', 21),
    L('Architectural shingle roof', 'SQ', 510),
    L('Standing seam metal roof', 'SQ', 1650),
    L('Insulation package (batts + blown attic)', 'SF', 2.25),
    L('Spray foam attic (open cell)', 'SF', 3.25),
    L('Drywall, hung & finished', 'SF', 2.85),
    L('Interior paint (new construction, spray)', 'SF', 3.25),
    L('LVP flooring, installed', 'SF', 5.75),
    L('Engineered hardwood, installed', 'SF', 10.5),
    L('Tile floor, installed', 'SF', 14),
    L('Carpet w/ pad, installed', 'SF', 4),
    L('Kitchen cabinets (semi-custom)', 'LF', 475),
    L('Countertops, granite / quartz Level 1', 'SF', 72),
    L('Custom tile shower', 'EA', 7500),
    L('Freestanding tub, installed', 'EA', 2750),
    L('Interior doors, trim & hardware package', 'SF', 4.5),
    L('Plumbing rough & trim (3 bath)', 'LS', 21500),
    L('Electrical rough & trim (200A)', 'SF', 8),
    L('HVAC heat pump system, ducted', 'EA', 12500),
    L('Garage door 16×7 insulated w/ opener', 'EA', 2600),
    L('Gutters 6" seamless', 'LF', 12.5),
    L('Covered porch', 'SF', 80),
    L('Screened porch', 'SF', 115),
    L('Deck, composite', 'SF', 68),
    L('Septic system (conventional)', 'LS', 9000),
    L('Well (drilled, pump, pressure tank)', 'LS', 12000),
    L('Final grade, seed & landscaping allowance', 'LS', 10000),
    L('Appliance allowance', 'LS', 8000),
    L('Lighting fixture allowance', 'LS', 4000),
    L('Builder general conditions / supervision', '%', 10),
  ],
  commercial: [
    L('Pre-engineered metal building kit', 'SF', 21),
    L('PEMB erection labor', 'SF', 11),
    L('6" reinforced slab w/ turn-down & vapor barrier', 'SF', 12.5),
    L('Building pad & site grading', 'LS', 25000),
    L('Aluminum storefront w/ 1" Low-E glazing', 'SF', 70),
    L('Storefront entrance pair, medium-stile w/ panic & closers', 'PR', 7250),
    L('Hollow-metal door & frame 3070 w/ hardware', 'EA', 2000),
    L('Overhead sectional door 12×12 insulated w/ opener', 'EA', 6000),
    L('Asphalt paving 2" surface on 6" ABC', 'SF', 4.5),
    L('Asphalt paving 3" on 8" ABC', 'SF', 5.75),
    L('Concrete paving 6" w/ rebar', 'SF', 11),
    L('ABC stone base, placed & compacted', 'TON', 38),
    L('Curb & gutter 24"', 'LF', 28),
    L('Concrete sidewalk 5\'', 'LF', 48),
    L('Parking striping (new layout)', 'SPACE', 14),
    L('ADA sign & post', 'EA', 275),
    L('Wheel stop', 'EA', 90),
    L('Sealcoat (2 coats) + crack fill', 'SF', 0.32),
    L('Site lighting pole 20\' w/ LED head, base & wiring', 'EA', 6000),
    L('Site electrical trench, conduit & wire', 'LF', 22),
    L('LED wall pack', 'EA', 675),
    L('Dumpster enclosure CMU w/ gates & pad', 'EA', 18000),
    L('Bollard, 6" concrete-filled, painted', 'EA', 1100),
    L('Type 1 hood system 10\' w/ Ansul & MUA', 'EA', 35000),
    L('Walk-in cooler 8×10, installed', 'EA', 17000),
    L('Walk-in freezer 8×10, installed', 'EA', 21500),
    L('Restaurant plumbing rough & trim (QSR)', 'LS', 67500),
    L('3-phase 400A service', 'LS', 18500),
    L('Rooftop HVAC unit w/ curb, per ton', 'EA', 3500),
    L('Fire sprinkler modification', 'SF', 5),
    L('Fire alarm system', 'SF', 3),
    L('ACT ceiling 2×4', 'SF', 5.5),
    L('Commercial LVT, installed', 'SF', 8),
    L('Metal stud & drywall partition (to deck)', 'LF', 115),
    L('Commercial ADA restroom, complete', 'EA', 17000),
    L('Bio-retention / stormwater facility', 'LS', 35000),
    L('General conditions / supervision', '%', 10),
    L('Building permit & plan review (commercial)', 'LS', 6000),
  ],
};

/** Flat list with division tags — for search and the AI tool. */
export function allLinePresets(): (LinePreset & { division: PresetDivision | 'general' })[] {
  const out: (LinePreset & { division: PresetDivision | 'general' })[] =
    GENERAL_LINE_PRESETS.map((p) => ({ ...p, division: 'general' as const }));
  for (const [div, list] of Object.entries(LINE_PRESETS_BY_DIVISION)) {
    for (const p of list) out.push({ ...p, division: div as PresetDivision });
  }
  return out;
}

export function searchLinePresets(q: string, division?: string, limit = 40) {
  const needle = q.trim().toLowerCase();
  return allLinePresets().filter((p) =>
    (!division || p.division === division || p.division === 'general') &&
    (!needle || p.description.toLowerCase().includes(needle))
  ).slice(0, limit);
}
